# http://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# => 4613732

require 'fiber'

max = 10_000_000
sum = 0

even_fib = Fiber.new do
  a,b = 1,1
  loop do
    Fiber.yield b if (b&1).zero?
    a,b = b,a+b
  end
end

while (n = even_fib.resume) < max
  sum += n
end

puts "Total: %d" % sum
